My branch
R1meq/Lab_5-Programming-part-1 pull request #1
Opened 2022-12-01 03:09 UTC by R1meq

2022-12-12 07:42 UTC, https999 commented on Land.cpp
> +Country Land::TopByPopulation(governmentType type) const
top *

2022-12-12 08:00 UTC, https999 requested changes

2022-12-12 08:00 UTC, https999 commented on Land.h
> +	Country TopByPopulation(governmentType type) const;
назва метода має бути  topByPopulation
перше слово по конвеншину для методів має бути з малої буки  ,а не з великої

2022-12-22 00:11 UTC, https999 commented on main.cpp
> +	const int topCount = 3;
Variables declared constexpr or const, and whose value is fixed for the duration of the program, are named with a leading "k" followed by mixed case.

2022-12-22 00:11 UTC, https999 commented on Land.cpp
> +	int topCount = count;
variable name lowercase with underscore  between words

2022-12-22 00:11 UTC, https999 commented on Country.cpp
> +	double sumPopulation = 0.0;
variable name lowercase with underscore  between words

2022-12-22 00:11 UTC, https999 commented on Country.cpp
> +	double sumArea = 0.0;
variable name lowercase with underscore  between words

2022-12-22 00:34 UTC, https999 approved these changes

2022-12-22 21:22 UTC, https999 commented
Тhe name of the commit messages have been fixed to be understandable

2022-12-22 21:23 UTC, R1meq commented
Тhe name of the commit messages have been fixed to be understandable

2022-12-22 21:25 UTC, https999 commented
Great job!

2023-03-29 14:00 UTC, closed without merging